services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: ["@mailer", "%locale%", "50%"]
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: ["@oc_platform.beta.html", "2016-03-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
    oc_platform.censorship_processor:
        class:     OC\PlatformBundle\Bigbrother\CensorshipProcessor
        arguments: ["@mailer"]
    oc_platform.censorship_listener:
        class:     OC\PlatformBundle\Bigbrother\CensorshipListener
        arguments: ["@oc_platform.censorship_processor", "[1, 2, 3]"]
        tags:
            - { name: kernel.event_listener, event: oc_platform.bigbrother.post_message, method: processMessage }
    oc_platform.json_paramconverter:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }