<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\QueryBuilder;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAdvertWithCategories(array $categoryNames)
  {
    $qb = $this->createQueryBuilder('a');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb->join('a.categories', 'c')->addSelect('c') ;


    // Puis on filtre sur le nom des catégories à l'aide d'un IN

    $qb->where($qb->expr()->in('c.name', $categoryNames));
    return $qb->getQuery()->getResult();

  }
}
